config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  get 'admin' => 'admin/admin#index'
  namespace :admin do
    resources :posts
  end


  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categoryposts
  has_many :posts, through: :categoryposts
end

app/models/categorypost.rb
class Categorypost < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :categoryposts
  has_many :categories, through: :categoryposts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  enum role: [:user, :admin , :super_admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :ensure_admin!
  def index

  end

  private
  def ensure_admin!
    unless current_user.admin?
      sign_out current_user
      redirect_to root_path
      return false
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  def index

  end

  def new
    @post = Post.new
    # authorize @post
    @category = Category.all

  end

  def create
      post  = post_params
      @post = Post.new(post)
      if(@post.save)
        params[:post][:category].each do |c|
          Categorypost.create(post_id: @post.id,category_id: c.to_i)
        end
      end
    render 'index'
  end

  def edit

  end

  def destroy

  end

  def update

  end
  private
    def post_params
      params.require(:post).permit(:title,:category,:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admin/index.html.erb
<h1>Admin Panel</h1>
<%= link_to "Admin Posts" ,admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>All admin posts</h1>
<%= link_to "New Post", new_admin_post_path %>

app/views/admin/posts/new.html.erb
<div class="col-6">
  <%= form_with model: @post, :url => admin_posts_path ,id: 'postsform' do |form| %>
      <div class="form-group">
        <label for="title">Post Title</label>
        <%=form.text_field :title ,id:'title', :class => "form-control" ,:placeholder => "Post Title"%>
      </div>

      <div class="form-group">
        <label for="category">Select Post Category</label>
        <h6>can select multiple categories</h6>
        <%= form.select(:category, @category.collect {|r| [ r.name.to_s, r.id ] },{include_hidden: false} ,{:multiple => true, :class => "form-control", :style => "width:250px;height:90px;" }) %>
      </div>
      <div class="form-group">
        <label for="content">Post Content</label>
        <%= form.text_area(:content, id: 'content',:class => "form-control", :placeholder => "Post content",:rows => "3")%>
      </div>
      <%= form.submit id:'postsubmit',:class => "btn btn-primary" %>
  <%end%>
</div>

app/views/application/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <h1>footer</h1>
  </div>
</div>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Project One</a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home",root_path ,:class => 'nav-item nav-link active' %>
      <% if user_signed_in? && current_user.admin? %>
          <%= link_to "Admin",admin_path,{:class => 'nav-link '} %>
      <% end %>

    </div>

  </div>
  <ul class="nav justify-content-end">
    <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Settings",edit_user_registration_path,{:class => 'nav-link '} %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out",destroy_user_session_path ,method: :delete,:class => 'nav-link ' %>
        </li>
    <%else%>
        <li class="nav-item">
          <%= link_to "Sign In",new_user_session_path,{:class => 'nav-link '} %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up',new_user_registration_path,{:class => 'nav-link signup'} %>
        </li>
    <%end%>
  </ul>
</nav>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectOne</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'header' %>
  </head>

  <body>
    <%= yield %>
    <%#= render 'footer' %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>